set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports muxout]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rx_cn]
set_property IOSTANDARD LVCMOS33 [get_ports sel_led]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk_1]
set_property IOSTANDARD LVCMOS33 [get_ports spi_clk_2]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs_1]
set_property IOSTANDARD LVCMOS33 [get_ports spi_cs_2]
set_property IOSTANDARD LVCMOS33 [get_ports spi_data]
set_property IOSTANDARD LVCMOS33 [get_ports spi_data_a_1]
set_property IOSTANDARD LVCMOS33 [get_ports spi_data_a_2]
set_property IOSTANDARD LVCMOS33 [get_ports spi_data_b_1]
set_property IOSTANDARD LVCMOS33 [get_ports spi_data_b_2]
set_property IOSTANDARD LVCMOS33 [get_ports spi_le1]
set_property IOSTANDARD LVCMOS33 [get_ports spi_le2]
set_property IOSTANDARD LVCMOS33 [get_ports sta_led]
set_property PACKAGE_PIN H16 [get_ports clk]
set_property PACKAGE_PIN T5 [get_ports muxout]
set_property PACKAGE_PIN Y17 [get_ports rst]
set_property PACKAGE_PIN T17 [get_ports rx_cn]
set_property PACKAGE_PIN L20 [get_ports sel_led]
set_property PACKAGE_PIN W6 [get_ports spi_clk]
set_property PACKAGE_PIN Y9 [get_ports spi_clk_1]
set_property PACKAGE_PIN Y13 [get_ports spi_clk_2]
set_property PACKAGE_PIN Y8 [get_ports spi_cs_1]
set_property PACKAGE_PIN W11 [get_ports spi_cs_2]
set_property PACKAGE_PIN U5 [get_ports spi_data]
set_property PACKAGE_PIN Y6 [get_ports spi_data_a_1]
set_property PACKAGE_PIN Y12 [get_ports spi_data_a_2]
set_property PACKAGE_PIN Y7 [get_ports spi_data_b_1]
set_property PACKAGE_PIN W8 [get_ports spi_data_b_2]
set_property PACKAGE_PIN V6 [get_ports spi_le1]
set_property PACKAGE_PIN U7 [get_ports spi_le2]
set_property PACKAGE_PIN L19 [get_ports sta_led]
connect_debug_port u_ila_0/probe1 [get_nets [list {top1/spi_read_2bit2/data_a[0]} {top1/spi_read_2bit2/data_a[1]} {top1/spi_read_2bit2/data_a[2]} {top1/spi_read_2bit2/data_a[3]} {top1/spi_read_2bit2/data_a[4]} {top1/spi_read_2bit2/data_a[5]} {top1/spi_read_2bit2/data_a[6]} {top1/spi_read_2bit2/data_a[7]} {top1/spi_read_2bit2/data_a[8]} {top1/spi_read_2bit2/data_a[9]} {top1/spi_read_2bit2/data_a[10]} {top1/spi_read_2bit2/data_a[11]} {top1/spi_read_2bit2/data_a[12]} {top1/spi_read_2bit2/data_a[13]} {top1/spi_read_2bit2/data_a[14]} {top1/spi_read_2bit2/data_a[15]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {top1/spi_read_2bit2/data_b[0]} {top1/spi_read_2bit2/data_b[1]} {top1/spi_read_2bit2/data_b[2]} {top1/spi_read_2bit2/data_b[3]} {top1/spi_read_2bit2/data_b[4]} {top1/spi_read_2bit2/data_b[5]} {top1/spi_read_2bit2/data_b[6]} {top1/spi_read_2bit2/data_b[7]} {top1/spi_read_2bit2/data_b[8]} {top1/spi_read_2bit2/data_b[9]} {top1/spi_read_2bit2/data_b[10]} {top1/spi_read_2bit2/data_b[11]} {top1/spi_read_2bit2/data_b[12]} {top1/spi_read_2bit2/data_b[13]} {top1/spi_read_2bit2/data_b[14]} {top1/spi_read_2bit2/data_b[15]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {top1/spi_read_2bit1/data_a[0]} {top1/spi_read_2bit1/data_a[1]} {top1/spi_read_2bit1/data_a[2]} {top1/spi_read_2bit1/data_a[3]} {top1/spi_read_2bit1/data_a[4]} {top1/spi_read_2bit1/data_a[5]} {top1/spi_read_2bit1/data_a[6]} {top1/spi_read_2bit1/data_a[7]} {top1/spi_read_2bit1/data_a[8]} {top1/spi_read_2bit1/data_a[9]} {top1/spi_read_2bit1/data_a[10]} {top1/spi_read_2bit1/data_a[11]} {top1/spi_read_2bit1/data_a[12]} {top1/spi_read_2bit1/data_a[13]} {top1/spi_read_2bit1/data_a[14]} {top1/spi_read_2bit1/data_a[15]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {top1/spi_read_2bit1/data_b[0]} {top1/spi_read_2bit1/data_b[1]} {top1/spi_read_2bit1/data_b[2]} {top1/spi_read_2bit1/data_b[3]} {top1/spi_read_2bit1/data_b[4]} {top1/spi_read_2bit1/data_b[5]} {top1/spi_read_2bit1/data_b[6]} {top1/spi_read_2bit1/data_b[7]} {top1/spi_read_2bit1/data_b[8]} {top1/spi_read_2bit1/data_b[9]} {top1/spi_read_2bit1/data_b[10]} {top1/spi_read_2bit1/data_b[11]} {top1/spi_read_2bit1/data_b[12]} {top1/spi_read_2bit1/data_b[13]} {top1/spi_read_2bit1/data_b[14]} {top1/spi_read_2bit1/data_b[15]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list top1/spi_read_2bit2/finish]]
connect_debug_port u_ila_0/probe8 [get_nets [list top1/spi_read_2bit2/muxout]]
connect_debug_port u_ila_0/probe9 [get_nets [list top1/spi_read_2bit1/muxout]]
connect_debug_port u_ila_0/probe10 [get_nets [list top1/spi_read_2bit1/spi_clk]]
connect_debug_port u_ila_0/probe11 [get_nets [list top1/spi_read_2bit2/spi_clk]]
connect_debug_port u_ila_0/probe12 [get_nets [list top1/spi_read_2bit2/spi_cs]]
connect_debug_port u_ila_0/probe13 [get_nets [list top1/spi_read_2bit1/spi_cs]]
connect_debug_port u_ila_0/probe14 [get_nets [list top1/spi_read_2bit1/spi_data_a]]
connect_debug_port u_ila_0/probe15 [get_nets [list top1/spi_read_2bit2/spi_data_a]]
connect_debug_port u_ila_0/probe16 [get_nets [list top1/spi_read_2bit1/spi_data_b]]
connect_debug_port u_ila_0/probe17 [get_nets [list top1/spi_read_2bit2/spi_data_b]]








connect_debug_port dbg_hub/clk [get_nets s_axis_aclk]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {dout[0]} {dout[1]} {dout[2]} {dout[3]} {dout[4]} {dout[5]} {dout[6]} {dout[7]} {dout[8]} {dout[9]} {dout[10]} {dout[11]} {dout[12]} {dout[13]} {dout[14]} {dout[15]} {dout[16]} {dout[17]} {dout[18]} {dout[19]} {dout[20]} {dout[21]} {dout[22]} {dout[23]} {dout[24]} {dout[25]} {dout[26]} {dout[27]} {dout[28]} {dout[29]} {dout[30]} {dout[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {din[0]} {din[1]} {din[2]} {din[3]} {din[4]} {din[5]} {din[6]} {din[7]} {din[8]} {din[9]} {din[10]} {din[11]} {din[12]} {din[13]} {din[14]} {din[15]} {din[16]} {din[17]} {din[18]} {din[19]} {din[20]} {din[21]} {din[22]} {din[23]} {din[24]} {din[25]} {din[26]} {din[27]} {din[28]} {din[29]} {din[30]} {din[31]} {din[32]} {din[33]} {din[34]} {din[35]} {din[36]} {din[37]} {din[38]} {din[39]} {din[40]} {din[41]} {din[42]} {din[43]} {din[44]} {din[45]} {din[46]} {din[47]} {din[48]} {din[49]} {din[50]} {din[51]} {din[52]} {din[53]} {din[54]} {din[55]} {din[56]} {din[57]} {din[58]} {din[59]} {din[60]} {din[61]} {din[62]} {din[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 3 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {state[0]} {state[1]} {state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 14 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {wr_cnt[0]} {wr_cnt[1]} {wr_cnt[2]} {wr_cnt[3]} {wr_cnt[4]} {wr_cnt[5]} {wr_cnt[6]} {wr_cnt[7]} {wr_cnt[8]} {wr_cnt[9]} {wr_cnt[10]} {wr_cnt[11]} {wr_cnt[12]} {wr_cnt[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list empty]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list fifo_rst]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list gpio_rtl_tri_o]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list prog_full]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list rd_clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list rd_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list S_AXIS_tlast]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list S_AXIS_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list S_AXIS_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list wr_clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list wr_en]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list FCLK_CLK0_div_4]]
set_property PULLUP true [get_ports muxout]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets FCLK_CLK0_div_4]
